/*
 * 	oled.c
 */

#include <stdio.h>
#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "ssd1366.h"
#include "font8x8_basic.h"

#include "oled.h"
#include "tdelay.h"
//static const char *TAG = "SSD1306";

#define NUM_CHAR_LINE_8		16
#define SPACES_16			"                "

/*
 * 	Static functions
 */

static void
done_i2c_command( i2c_cmd_handle_t cmd )
{
	i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	i2c_cmd_link_delete(cmd);
}

static void
set_line( unsigned line )
{
	i2c_cmd_handle_t cmd;

	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);

	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd, 0x00, true); // reset column
	i2c_master_write_byte(cmd, 0x10, true); // page addessing mode
	i2c_master_write_byte(cmd, 0xB0 | line, true); // reset page

	i2c_master_stop(cmd);
	done_i2c_command( cmd );
}

static void
send_line( const char *text, int num )
{
	const char *p;
	i2c_cmd_handle_t cmd;

	for( p = text; p < text + num; ++p )
	{
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)*p], 8, true);
		i2c_master_stop(cmd);
		done_i2c_command( cmd );
	}
}

/*
 * 	Public functions
 */

void oled_init( void )
{
	i2c_cmd_handle_t cmd;
	
	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_CHARGE_PUMP, true);
	i2c_master_write_byte(cmd, 0x14, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_SEGMENT_REMAP, true); // reverse left-right mapping
	i2c_master_write_byte(cmd, OLED_CMD_SET_COM_SCAN_MODE, true); // reverse up-bottom mapping

	i2c_master_write_byte(cmd, OLED_CMD_DISPLAY_ON, true);
	i2c_master_stop(cmd);

	done_i2c_command( cmd );
	tdelay(100);
}

void
oled_clear( void )
{
	uint8_t zero[128];
	uint8_t i;
	i2c_cmd_handle_t cmd;

	memset( zero, 0, sizeof(zero) );

	for ( i = 0; i < 8; ++i )
	{
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, zero, 128, true);
		i2c_master_stop(cmd);
		done_i2c_command( cmd );
		tdelay(10);
	}
}

void
oled_contrast( unsigned contrast )
{
	i2c_cmd_handle_t cmd;

	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd, OLED_CMD_SET_CONTRAST, true);
	i2c_master_write_byte(cmd, contrast, true);
	i2c_master_stop(cmd);

	done_i2c_command( cmd );
	tdelay(10);
}


void
oled_text( unsigned line, const char *text )
{
	int num;

	line %= 8;	/*Only 8 lines	*/

	set_line( line );
	send_line( SPACES_16, NUM_CHAR_LINE_8 );

	set_line( line );
	if( ( num = strlen( text ) ) > NUM_CHAR_LINE_8 )
		num = NUM_CHAR_LINE_8;
	send_line( text, num );
}

	

